### ISSUE TITLE
v.3.0.1 is out plz bump it

### ISSUE THREAD

**Issue by chrillep** [retlehs/kinsta-mu-plugins#13]
just happend to notice this inside the plugin files.
https://kinsta.com/kinsta-tools/kinsta-mu-plugins.zip

nothing on the changelog page https://kinsta.com/changelog/mu-plugin-changelog/

**Comment by mike-sheppard** [comment]
Thanks @chrillep should be updated 🙏

**Comment by chrillep** [comment]
@mike-sheppard changelog updated, if you want to update the release notes @ https://github.com/retlehs/kinsta-mu-plugins/releases/tag/3.0.1

https://kinsta.com/changelog/mu-plugin-changelog/#301-october-9-2023

<h2 id="301-october-9-2023" class="has-anchor-hash">3.0.1 (October 9, 2023)<a class="anchor-hash" href="#301-october-9-2023" aria-hidden="true"><svg class="icon icon--link" aria-hidden="true" focusable="false" viewBox="0 0 32 32"><use xlink:href="https://kinsta.com/wp-content/themes/kinsta/dist/sprite.svg?v=2260adc4bca3c67adf39ad4283404bab#link"></use></svg></a></h2>
<h3 id="added-16" class="has-anchor-hash">Added<a class="anchor-hash" href="#added-16" aria-hidden="true"><svg class="icon icon--link" aria-hidden="true" focusable="false" viewBox="0 0 32 32"><use xlink:href="https://kinsta.com/wp-content/themes/kinsta/dist/sprite.svg?v=2260adc4bca3c67adf39ad4283404bab#link"></use></svg></a></h3>
<ul>
<li>CDN Cache clearing functionality</li>
<li>Properly detect Kinsta Cache headers in Site Health Check when Edge Cache is disabled</li>
</ul>
<h3 id="changed-23" class="has-anchor-hash">Changed<a class="anchor-hash" href="#changed-23" aria-hidden="true"><svg class="icon icon--link" aria-hidden="true" focusable="false" viewBox="0 0 32 32"><use xlink:href="https://kinsta.com/wp-content/themes/kinsta/dist/sprite.svg?v=2260adc4bca3c67adf39ad4283404bab#link"></use></svg></a></h3>
<ul>
<li><code>KINSTAMU_ROLE</code>is now deprecated in favor of <code>KINSTAMU_CAPABILITY</code></li>
<li>Clean up and standardize wording in WP-CLI output</li>
<li><code>wp kinsta cache purge</code>now takes<code>--site</code>,<code>--cdn</code>,<code>--object</code>, and <code>--all</code>to clear all the various forms of cache</li>
</ul>
<h3 id="fixed-12" class="has-anchor-hash">Fixed<a class="anchor-hash" href="#fixed-12" aria-hidden="true"><svg class="icon icon--link" aria-hidden="true" focusable="false" viewBox="0 0 32 32"><use xlink:href="https://kinsta.com/wp-content/themes/kinsta/dist/sprite.svg?v=2260adc4bca3c67adf39ad4283404bab#link"></use></svg></a></h3>
<ul>
<li>“Clear All Caches” from the admin bar now works properly</li>
<li>Fixed PHP 8.2 deprecation notices</li>
</ul>

**Comment by mike-sheppard** [comment]
Nice one @chrillep, release notes updated https://github.com/retlehs/kinsta-mu-plugins/releases/tag/3.0.1 ✅
