### ISSUE TITLE
Unable to fetch v 3.1.0 or 3.1.1 with composer. 

### ISSUE THREAD

**Issue by marolsson** [retlehs/kinsta-mu-plugins#16]
Having the following settings in composer.json only allows to fetch the 3.0.1 version as the most recent. 
```
{
    "type": "vcs",
    "url": "git@github.com:retlehs/kinsta-mu-plugins"
}
```
Can we add the two latest versions as well so the plugin can be updated without needing to target specific versions in the composer.json file?

**Comment by mike-sheppard** [comment]
[https://github.com/retlehs/kinsta-mu-plugins/releases/tag/3.1.1](3.1.1) released
