### ISSUE TITLE
WP_PLUGIN_URL instead of WPMU_PLUGIN_URL in shared_resource_url()

### ISSUE THREAD

**Issue by valentinge** [retlehs/kinsta-mu-plugins#6]
Good day,

thank you for the useful plugin and overall fantastic service you guys at Kinsta provide!

I would like to suggest a small change that will allow users like me download and use your plugin from the default plugin directory. In `shared_resource_url()` I would use `WP_PLUGIN_URL` instead of `WPMU_PLUGIN_URL` if `__DIR__` doesn't contain `mu-plugins`. I haven't testes my suggestion but I think that even if it doesn't have the immediate desired effect with some small tweaking it will work.

Kind regards,
Valentin

**Comment by mike-sheppard** [comment]
hey @valentinge - this is simply a mirror of the Kinsta plugin to support Composer/versioning - please get in touch with Kinsta support directly. Hopefully, they'll create a public repo soon if we keep bugging them for it! 🤞
