### ISSUE TITLE
PHP Deprecated  message

### ISSUE THREAD

**Issue by moduca** [retlehs/kinsta-mu-plugins#9]
Hi, I am getting a deprecated message on my logs:

Required parameter $options follows optional parameter $info in /www/xxx/public/wp-content/mu-plugins/kinsta-mu-plugins/shared/class-shared.php on line 148

`public static function kinsta_select_field( $option_name, $name, $value, $label, $info = false, $options ) {
     ...
     ...
}`

**Comment by mike-sheppard** [comment]
hey @moduca  - this is simply a mirror of the Kinsta plugin to support Composer/versioning - please get in touch with Kinsta support directly. Hopefully, they'll create a public repo soon if we keep bugging them for it! 🤞
